apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-con
        image: 217026896236.dkr.ecr.ap-northeast-2.amazonaws.com/web-argo:2
